name = "mcp-actual-proxy"
main = "src/index.js"
compatibility_date = "2025-12-01"

[[routes]]
pattern = "mcp-actual.dinamopro.com"
custom_domain = true

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "0a844004ce2f467d91b576cca030649f"

[vars]
CLIENT_ID = "claude-mcp-client"
ISSUER = "https://mcp-actual.dinamopro.com"
MCP_BACKEND_URL = "https://mcp-actual-internal.dinamopro.com/mcp"